---
title: "final_assignment"
format: html
---

For the course of the MEDS Environmental Modeling class at UCSB, we have learned the step-by-step process of developing, testing, and analyzing results of a model for environmental problem solving contexts. In this project, we will develop a clear, well-structured plan for using a model in a hypothetical environmental context.

## Modeling Question

Inflammatory bowel disease (IBD) and irritable bowel syndrome (IBS) affect millions of people worldwide, impacting quality of life and health outcomes. There is research indicating a healthy gut microbiome can both decrease symptoms and perhaps decrease risk of developing either disease. We are interested in the impact of probiotic supplements, such as kefir, on risk of inflammatory bowel disease and irritable bowel syndrome. Kefir increases the gut microbiome diversity, which is thought to decrease gastrointestinal (GI) disease risk, specifically by decreasing the concentration of c-reactive protein (CRP) levels in an individual. Elevated CRP levels are bio indicators of chronic inflammation and used to diagnose IBD and IBS. We will use a three-part modeling framework to examine GI disease risk: first, identifying the optimal kefir intake to maximize GI tract microbiome diversity; second, determining the level of microbiome diversity necessary to bring CRP concentrations within a clinically healthy range; and third, estimating GI disease risk as a function of CRP alongside genetic risk, demographic factors, and disease activity.

## Conceptual Model

## Model Design

Our model consists of 3 submodels, one that will predict GI microbiome diversity based on probiotic supplementation, one that will take that GI microbiome diversity and generate a CRP value, and another submodel that takes the predicted CRP and calculates disease risk.

### ***Microbiome Diversity Model:*** 

**Inputs**:

-   Dietary fiber

-   Demographic data (age, sex, etc)

-   Antibiotic use

-   Calorie intake

-   Probiotic supplement

**Outputs**:

-   Microbe diversity

### ***CRP Model:***

Inputs:

-   Microbiome diversity (previous model)

-   Demographic data (age, sex, etc)

-   Antibiotic use

-   Calorie intake

Outputs:

-   CRP

### ***GI Disease Risk Model:*** 

**Inputs**:

-   Genetic risk

-   CRP (from previous model)

-   Demographic data (age, sex, etc.)

-   Disease activity (if any)


**Outputs**:

-   GI disease risk

All of these models will be put together in a wrapper to fully calculate GI disease risk based on probiotic use input. They are all forms of mathematical, deterministic and static models.

This hypothetical model was inspired by the work done by Ma et. al. 2021.

In order to test model performance, we will first test the model with a data set (source: Ashwin et. al 2013) consistent of around 400 sample units with information of disease status and diet (fiber, protein, etc) over 26 years. We can input this data set (diet, demographic data, calorie intake, antibiotic use) into our model without including probiotics as a metric, and our output of GI disease status can be interpolated into risk and should look appropriate.

## Analysis Plan

In order to answer our question of how GI disease risk is influenced by probiotic supplementation, we would want to implement our model with varying levels of probiotic supplements and first see how disease risk responds. Do we expect CRP to increase exponentially and level off, or perhaps follow a normal growth rate path? We can vary all parameters for every level of probiotic supplementation through sensitivity testing with Sobol to investigate how different demographics may respond differently to probiotic supplementation. We would vary parameters based on literature and data used for validation testing. Sensitivity of each parameter can be visualized individually against GI disease risk, along with sobol indices produced to assess parameter importance to GI disease risk. Sampled parameter sets can be visualized as a line graph with probiotic use of the x axis and disease risk on the y axis. Ideally, we will find an optimal probiotic supplementation that provides the best risk reduction.

## Assumptions

We are assuming that the gut microbiome, and ONLY the gut microbiome, are contributing to disease risk reduction. While we include other parameters into our model, ultimately they all contribute to the gut microbiome which we assume directly influences disease risk. While there are certainly other factors, they are not included in this model. We are also assuming CRP as a proxy for disease risk. We are not taking into account time factors, such as any trends in probiotic use over time or fluctuations of health/age/disease activity over time, and rather assessing the cummulative impact of probiotics on disease risk. Finally, we are not including any medication being taken by those with the disease that may be influencing disease activity significantly.

## Sources

Ma, W., Nguyen, L.H., Song, M. et al. Dietary fiber intake, the gut microbiome, and chronic systemic inflammation in a cohort of adult men. Genome Med 13, 102 (2021). https://doi.org/10.1186/s13073-021-00921-y

Ashwin N. Ananthakrishnan, Hamed Khalili, Gauree G. Konijeti, Leslie M. Higuchi, Punyanganie de Silva, Joshua R. Korzenik, Charles S. Fuchs, Walter C. Willett, James M. Richter, Andrew T. Chan,
A Prospective Study of Long-term Intake of Dietary Fiber and Risk of Crohn's Disease and Ulcerative Colitis, Gastroenterology, 145-5, 2013, 970-977, 0016-5085, https://doi.org/10.1053/j.gastro.2013.07.050