---
title: "HW7_twovariable_dynamic"
format: html
---

```{r}
library(tidyverse)
library(here)
```

```{r}
source(here("R", "lotvmodK.R"))

print(lotvmodK)
```

```{r}
# initial conditions
currpop <- c(prey = 10, pred = 1)

# set parameter list
pars <- c(rprey = 0.95, alpha = 0.01, eff = 0.6, pmort = 0.4, K = 2000, hunt = 0.5, threshold = 20)

# times when you want to evaluate
days <- seq(from = 1, to = 500)

# run our differential equation solver
res <- ode(func = lotvmodK, y = currpop, times = days, parms = pars)

# rearrange for plotting
resl <- as.data.frame(res) %>% pivot_longer(-time, names_to = "species", values_to = "pop")

# graph both populations over time
p1 <- ggplot(resl, aes(time, pop, col = species)) +
  geom_line()
p1

# also look at relationships between preditor and prey population and use color for time
# I will remove the legend here to make it easier to see
p2 <- ggplot(as.data.frame(res), aes(pred, prey, col = (round(time / 10)))) +
  geom_point() +
  theme(legend.position = "none")
p2
p2 <- ggplot(as.data.frame(res), aes(pred, prey, col = as.factor(round(time / 10)))) +
  geom_point() +
  theme(legend.position = "none")
p2
ggarrange(p1, p2)
```

Sobol Sensitivity Testing

```{r}
# want to learn about sensitivity to growth rate (r) and carrying capacity
# set the number of parameters
np <- 200
K <- rnorm(mean = 150, sd = 20, n = np)
rprey <- runif(min = 0.01, max = 0.3, n = np)
alpha <- runif(min = 0.1, max = 0.4, n = np)
eff <- rnorm(mean = 0.3, sd = 0.01, n = np)
pmort <- runif(min = 0.01, max = 0.45, n = np)
hunt <- runif(min = 0.01, max = 1, n = np)
threshold <- runif(min = 1, max = 300, n = np)

X1 <- cbind.data.frame(rprey = rprey, K = K, alpha = alpha, eff = eff, pmort = pmort, hunt = hunt, thresh = thresh)

# repeat to get our second set of samples
np <- 200
K <- rnorm(mean = 150, sd = 20, n = np)
rprey <- runif(min = 0.01, max = 0.3, n = np)
alpha <- runif(min = 0.1, max = 0.4, n = np)
eff <- rnorm(mean = 0.3, sd = 0.01, n = np)
pmort <- runif(min = 0.01, max = 0.45, n = np)
hunt <- runif(min = 0.01, max = 1, n = np)
threshold <- runif(min = 1, max = 300, n = np)

X2 <- cbind.data.frame(rprey = rprey, K = K, alpha = alpha, eff = eff, pmort = pmort, hunt = hunt, thresh = thresh)

# create our sobel object and get sets ofparameters for running the model
sens_PP <- sobolSalt(model = NULL, X1, X2, nboot = 300)

# name parameter sets...
colnames(sens_PP$X) <- c("rprey", "K", "alpha", "eff", "pmort", "hunt")

# our metrics
# lets say we  want the maximum and minimum  of both predictor and prey

compute_metrics <- function(result) {
  maxprey <- max(result$prey)
  minprey <- min(result$prey)
  return(list(maxprey = maxprey, minprey = minprey))
}

# build a wrapper function

p_wrapper <- function(rprey, alpha, eff, pmort, K, hunt, currpop, days, func) {
  parms <- list(rprey = rprey, alpha = alpha, eff = eff, pmort = pmort, K = K, hunt = hunt)
  result <- ode(y = currpop, times = days, func = func, parms = parms)
  colnames(result) <- c("time", "prey", "pred", "hunt")
  # get metrics
  metrics <- compute_metrics(as.data.frame(result))
}
```


```{r}
# run our model for all parameters and extract the results
currpop <- c(prey = 1, pred = 1)
days <- seq(from = 1, to = 500)
allresults <- as.data.frame(sens_PP$X) %>% 
    pmap(p_wrapper, currpop = currpop, days = days, func = lotvmodK)

# take results back to unlisted form
allres <- allresults %>% map_dfr(`[`, c("maxprey", "minprey"))


# range of response across parameter uncertainty
allresl <- allres %>% gather(key = "metric", value = "pop")
ggplot(allresl, aes(metric, pop)) +
  geom_boxplot()

# dealing with different scales
ggplot(allresl, aes(metric, pop, col = metric)) +
  geom_boxplot() +
  facet_wrap(~metric, scales = "free")
# plot cummulative densities

ggplot(allresl, aes(pop, col = metric)) +
  stat_ecdf(geom = "line") +
  facet_wrap(~metric, scales = "free")
```

